Algoritmo "Conversao de temperatura"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2020
Var
C, F, media: real

Inicio
escreval ("digite os graus C:")
leia(C)
leia(F)

C <-
F <- (9*C+160) / 5





Fimalgoritmo