Algoritmo "Volume da lata"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2020
Var
vol, alt, raio: real


Inicio
Escreval("insira a altura da lata")
leia(alt)

Escreval("Insira o raio da lata:")
Leia(raio)

vol <- 3.14 * (raio*raio) * alt
Escreval("O volume da lata de óleo é:",vol)




Fimalgoritmo